"""add phone number

Revision ID: 75d927162932
Revises: c1fd952081f0
Create Date: 2026-03-17 02:05:54.844445

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "75d927162932"
down_revision: Union[str, Sequence[str], None] = "c1fd952081f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
