"""add auto-vote

Revision ID: c1fd952081f0
Revises: 045b52e6d771
Create Date: 2026-03-17 02:03:26.301230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c1fd952081f0"
down_revision: Union[str, Sequence[str], None] = "045b52e6d771"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name="votes_post_fkey", onupdate="NO ACTION"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="votes_user_fkey", onupdate="NO ACTION"
        ),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("votes")
    # ### end Alembic commands ###
